FROM node:23.11-alpine

WORKDIR /var/www

# Install vite globally
RUN npm install -g vite

# Install dependencies first
COPY package*.json ./
RUN npm cache clean --force && \
    rm -rf node_modules package-lock.json && \
    npm install && \
    npm audit fix --force

# Copy the rest of the application
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
