FROM adminer:latest

LABEL maintainer="Hendro Wibowo <hendro.wibowo@wearesocial.net>"

# Add volume for sessions to allow session persistence
VOLUME /sessions

USER adminer

# We expose Adminer on port 8080 (Adminer's default)
EXPOSE 8080
